package com.dnebinger.liferay.vaadin.sample;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.VerticalLayout;

public class LiferayUsersComponent extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private TabSheet userPages;
	@AutoGenerated
	private UserDetailComponent userDetailTab;
	@AutoGenerated
	private UserListComponent userListTab;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public LiferayUsersComponent(UsersUI uui) {
		buildMainLayout(uui);
		setCompositionRoot(mainLayout);
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout(UsersUI uui) {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// userPages
		userPages = buildUserPages(uui);
		mainLayout.addComponent(userPages);

		return mainLayout;
	}

	@AutoGenerated
	private TabSheet buildUserPages(UsersUI uui) {
		// common part: create layout
		userPages = new TabSheet();
		userPages.setImmediate(true);
		userPages.setWidth("100.0%");
		userPages.setHeight("100%");

		// hide the tabs because we don't want the user switching manually.
		userPages.hideTabs(true);

		// userListTab
		userListTab = new UserListComponent();
		userListTab.setImmediate(false);
		userListTab.setWidth("100.0%");
		userListTab.setHeight("100%");
		userPages.addTab(userListTab, "List", null);

		// userDetailTab
		userDetailTab = new UserDetailComponent(uui);
		userDetailTab.setImmediate(false);
		userDetailTab.setWidth("100.0%");
		userDetailTab.setHeight("100%");
		userPages.addTab(userDetailTab, "Detail", null);

		return userPages;
	}

	/**
	 * switchToListView: Switches to the list view tab.
	 */
	public void switchToListView() {
		// choose the list tab.
		userPages.setSelectedTab(userListTab);
	}

	/**
	 * switchToDetailView: Switches to the detail view tab.
	 * @param userId The user id to display details for.
	 */
	public void switchToDetailView(final long userId) {
		// choose the details tab...
		userPages.setSelectedTab(userDetailTab);

		// update the detail view for the selected user.
		userDetailTab.updateFromUser(userId);
	}
}
